apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: rkmiaiqqy-go 
  janus-idp.io/tekton: rkmiaiqqy-go
  backstage.io/kubernetes-id: rkmiaiqqy-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rkmiaiqqy-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml