apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rkmiaiqqy-go-gitops
  description: This is GitOps manifest for rkmiaiqqy-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=rkmiaiqqy-go
    backstage.io/kubernetes-id: rkmiaiqqy-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: rkmiaiqqy-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rkmiaiqqy-go
